version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gitlab_readiness?sslmode=disable
      - DATABASE_TYPE=postgres
    depends_on:
      - db
    network_mode: service:db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gitlab_readiness

volumes:
  postgres-data: